cellprob_threshold: 0.1
channel_axis: .nan
channel_nuclei: 0
channel_segment: 0
diameter: 50
do_3D: true
flow_threshold: 0.5
interp: false
invert: false
jaccard_cellpose: 0.3273679660939884
jaccard_sklearn: 0.971190481252862
max_size_fraction: 0.5
min_size: 15
model_name: cyto3
niter: 100
normalize: true
stitch_threshold: 0.0
tile_overlap: 0.1
